### ISSUE TITLE
Day/Night Cycle

### ISSUE THREAD

**Issue by radmint** [CozyClub/OGAM-June#13]

**Comment by DarkSapra** [comment]
Starting to work on it

**Comment by DarkSapra** [comment]
- [ ] Hour events
- [ ] Minute events
- [ ] Time stopping
- [ ] Sun/moon cycle

**Comment by DarkSapra** [comment]
Routines for NPCs

**Comment by DarkSapra** [comment]
- [ ] Routines for NPCs
- [ ] Smoother Routines
- [ ] Routine Variations

**Comment by DarkSapra** [comment]
The Day Night Cycle is working. I close this issue, if any problem arises, feel free to open it again.
