### ISSUE TITLE
Picture confirmation

### ISSUE THREAD

**Issue by croconut** [CozyClub/OGAM-June#3]
We'll want to confirm the picture you took is the one you want to save. Should be something like:
 
1. game confirms photo would contain a capture target or alert player, no target found
2. projects render texture to screen
3. game time stops
4. player confirms photo is good
5. save to disk
6. advance questline? (not implementing here)

**Comment by croconut** [comment]
After playing, I think we should also add a live picture preview to the UI while we're preparing the photo (current controls is holding space)

**Comment by radmint** [comment]
@croconut I agree with that and it might be good to do that when we have the player controller finalized
