### ISSUE TITLE
Main Scene with too much clutter

### ISSUE THREAD

**Issue by DarkSapra** [CozyClub/OGAM-June#34]
I was thinking that to avoid cluttery, we could try to make different scenes for each other.

**Comment by radmint** [comment]
Can you add more details to this? What do you mean?

**Comment by DarkSapra** [comment]
Never mind, it has been already fixed, with the recent pushes/commits, there have been different scenes for different peoples work, and the scene itself is not cluttered of objects

**Comment by DarkSapra** [comment]
Closing the issue
